apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-app-secret
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/minScale: "0"
    run.googleapis.com/maxScale: "1"
    run.googleapis.com/invoker-iam-disabled: "true"
    run.googleapis.com/scalingMode: automatic
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/shukawam/shukawam-repo/python-app-secret:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: SECRET # 指定した環境変数名で設定される
              valueFrom:
                secretKeyRef: # Secret Managerから参照する
                  name: example-secret # Secret Managerで作成したSecret名
                  key: "2" # Secretのバージョンを指定する
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: secret-key
              mountPath: /secret # コンテナ内のどのディレクトリにマウントするかを指定する
      volumes:
        - name: secret-key
          secret:
            secretName: example-secret-file # Secret Managerで作成したSecret名
            items:
              - key: "1" # Secretのバージョンを指定する
                path: secret.json # マウントされるファイル名を指定する
  traffic:
    - percent: 100
      latestRevision: true
