apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-app
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/minScale: "0"
    run.googleapis.com/maxScale: "1"
    run.googleapis.com/invoker-iam-disabled: "true"
    run.googleapis.com/scalingMode: automatic
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/shukawam/shukawam-repo/python-app:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
  traffic:
    - percent: 100
      latestRevision: true
