name: Build and Push

on:
  # mainブランチにプッシュしたことをトリガーに実行
  push:
    branches:
      - main
  # pull requestが起票・更新されたことをトリガーに実行
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build-and-push.yaml"
      - "**.md"
    types:
      - opened
      - synchronize
  # 手動でトリガーを実行
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint w/ flake8
        run: |
          flake8 app.py --count --select E9,F63,F7,F82 --show-source --statistics
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test w/ Pytest
        run: |
          pytest
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # Linter, Unit Testの完了が必要
    needs:
      - flake8
      - pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Google GitHub Actions Auth
        id: google-auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/${{ secrets.GOOGLE_CLOUD_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc-provider'
          service_account: 'github-actions@${{ secrets.GOOGLE_CLOUD_ID }}.iam.gserviceaccount.com'
      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v1
        with:
          username: oauth2accesstoken
          password: ${{ steps.google-auth.outputs.access_token }}
          registry: asia-northeast1-docker.pkg.dev
      - name: OCI(Open Container Initiative) image build and push
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_ID }}/python-app:${{ github.sha }}
            asia-northeast1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_ID }}/python-app:latest
      - name: Deploy app to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: python-app
          region: asia-northeast1
          image: asia-northeast1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_ID }}/python-app:${{ github.sha }}
          metadata: ./services/python-app.yaml
