name: Flake8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --yograde pip
          pip install -r requirements.txt
      - name: Lint w/ flake8
        run: |
          flake8 app.py --count --select E9,F63,F7,F82 --show-source --statistics
